### ISSUE TITLE
Metron-Setup Script

### ISSUE THREAD

**Issue by mackhendricks** [flyballlabs/threatdetectionservice#19]
This script is responsible for configuring a Metron installation to work with the Threat Management Platform (TMP).  The first release is focused on making it work with the Metron Quickstart VM.

**Comment by JonZeolla** [comment]
I've done something very similar to this which has some more functions, that you may be able to use as a foundation and then add on your TMP stuff.  It only currently works on CentOS 6, but I'm working to get it up and running on CentOS 7 and to support the docker stuff.  

https://github.com/JonZeolla/lab-SecurityDataAnalysis/blob/master/setup/setup.sh

**Comment by mackhendricks** [comment]
This is super cool… we are going to review and see if we can use this…we are on Metron 0.3.0.  What version was your script developed for?

**Comment by JonZeolla** [comment]
It was developed for 0.3.0 but it should work for 0.3.1 as well as soon as it's released.  In fact I'm testing that tomorrow.
