### ISSUE TITLE
Adding Notification setting for a user

### ISSUE THREAD

**Issue by mackhendricks** [flyballlabs/threatdetectionservice#24]
A user should be able to specify how they want notification data to be sent.  Per the following ways"

Email: 

-provide an email field
-provide a score level.  For example, only send messages when the score is 5 or less

SMS:

- provide a phone number
- provide a score level in which to be notified.  For example, only send  SMS messages when the score is 5 or more

**Comment by devopsec** [comment]
The backend support for these functions are in my repo and need merged into the master.
Such as notification type, phone number, etc.. Those mods seem to have not been merged to master..
